# Generated by Django 4.2.26 on 2025-11-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='clarification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='clarification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='clarification_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('on_hold', 'On Hold')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('need_info', 'Need More Information')], default='pending', max_length=20),
        ),
    ]
