# Generated by Django 4.2.26 on 2025-11-20 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('vendor_address', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('payment_terms', models.TextField(blank=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('ai_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_metadata', to='requests.purchaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
