# Generated by Django 4.2.26 on 2025-11-22 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_purchaserequest_clarification_message_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('items', models.JSONField(blank=True, default=list)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('discrepancy', 'Has Discrepancies'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_metadata', to='requests.purchaserequest')),
            ],
        ),
    ]
